### ISSUE TITLE
Why does it need to use the PHP native mail() function?

### ISSUE THREAD

**Issue by mudrd8mz** [learningworks/moodle-local_pages#12]
I am wondering what is the use case for using the direct low level access to the PHP's `mail()` function via the `custom_email` setting. As far as I can see, it only exposes the plugin to a wide range of various security risks including SMTP header injection, spam risk etc. Is that really needed?

**Comment by digitalskill** [comment]
There are some environments used that required specific PHP headers to be present and to use the PHP mail. This is when forms on the pages plugin needed to go to a different address and use PHP mail rather than Moodle email as the settings were different. It's an extreme edge case that was needed by our clients.

**Comment by mudrd8mz** [comment]
Thanks for the info. However, I don't think that the need for custom SMTP headers justifies the potentially dangerous feature. If you need them, you should still able to provide custom SMTP headers even via the common `email_to_user()` feature. Please see https://github.com/moodle/moodle/blob/v3.4.0/lib/moodlelib.php#L5858-L5867 for details.

**Comment by digitalskill** [comment]
Thanks Mudrd8mz, Agree. Removing the custom SMTP header option from the pages plugin.

Cheers
